import 'dart:convert';
import 'dart:typed_data';

/// At-rest obfuscation for operational values (endpoint, attribution key,
/// client stamp fragments).
///
/// Deliberately built from ordinary primitives — `base64` plus one masking
/// pass keyed by position. The key material is the app identity, so the same
/// values can be regenerated by `tool/encode_flow_values.dart` at any time.
class AshCodec {
  const AshCodec._();

  static const String keySource = 'com.lavawake.rushgame';

  static const int _stride = 23;
  static const int _offset = 5;

  static String reveal(String packed) => utf8.decode(_mask(base64Decode(packed)));

  /// Encoder half, used only by `tool/encode_flow_values.dart`.
  static String conceal(String plain) => base64Encode(_mask(utf8.encode(plain)));

  static Uint8List _mask(List<int> input) {
    final key = utf8.encode(keySource);
    final out = Uint8List(input.length);
    for (var i = 0; i < input.length; i++) {
      out[i] = input[i] ^ key[(i * _stride + _offset) % key.length];
    }
    return out;
  }
}
